"""Solar System's views, from the Sun outward; each world's views in the order the tour shows them, best first.
kind: disc (a whole world on black), closeup (fills the screen), live (TheSun or TheMoon).
focus: where the zoom heads, as fractions of the cut photo from its top left; zoom overrides the Zoom setting."""

HEADER = """# Solar System's views, cut by prep.py from these originals. Public domain, CC BY or CC BY-SA; CC BY and CC BY-SA
# require this attribution. file\tbody\tcredit\tlicence\tsource\tcaption\tkind\tfocus x,y[,zoom]
"""

PHOTOS = [
    # The Sun
    dict(kind='live', body='The Sun', credit='NASA/SDO and the AIA, EVE and HMI science teams, via Helioviewer',
         licence='Public domain', source='https://helioviewer.org', caption="Today, from NASA's Solar Dynamics Observatory"),
    dict(name='sun-orbiter', src='inner/sun-disc-solarorbiter-eui-widest-2025.jpg', kind='disc', body='The Sun', at=(0.35, 0.55), cap=4800, zoom=1.5,
         credit='ESA & NASA/Solar Orbiter/EUI Team, E. Kraaikamp (ROB)', licence='CC BY-SA 3.0 IGO',
         source='https://www.esa.int/ESA_Multimedia/Images/2025/04/Solar_Orbiter_s_widest_high-res_view_of_the_Sun',
         caption='Solar Orbiter, 2025 · extreme ultraviolet'),
    dict(name='sun-visible', src='inner/sun-disc-solarorbiter-phi-visible-2024.jpg', kind='disc', body='The Sun', at=(0.23, 0.58), cap=4000, zoom=1.5,
         credit='ESA & NASA/Solar Orbiter/PHI Team; image processing by PHI Team members at MPS', licence='CC BY-SA 3.0 IGO',
         source='https://www.esa.int/ESA_Multimedia/Images/2024/11/PHI_s_view_of_the_Sun_in_visible_light',
         caption='Sunspots · Solar Orbiter, 2023'),
    dict(name='sun-eruption', feather=0.06, src='inner/sun-disc-sdo-cme-20120831.jpg', kind='disc', body='The Sun', at=(0.08, 0.72),
         credit='NASA/GSFC/SDO', licence='Public domain', source='https://images.nasa.gov/details/GSFC_20171208_Archive_e001661',
         caption='A filament erupts · Solar Dynamics Observatory, 31 August 2012 · ultraviolet'),
    dict(name='sun-spot', src='inner/sun-closeup-dkist-sunspot450-2021.jpg', kind='closeup', body='The Sun', at=(0.5, 0.5),
         credit='NSF/NSO/AURA', licence='CC BY 4.0', source='https://noirlab.edu/public/images/NSO-DKIST-spot450_full1-CC/',
         caption='A sunspot · Inouye Solar Telescope, 2021'),
    dict(name='sun-filament', src='inner/sun-disc-sdo-filament-20150210.jpg', kind='disc', body='The Sun', at=(0.67, 0.52),
         credit='NASA/SDO', licence='Public domain', source='https://images.nasa.gov/details/GSFC_20171208_Archive_e000790',
         caption='A dark filament · Solar Dynamics Observatory, 2015 · ultraviolet'),
    dict(name='sun-granules', src='inner/sun-closeup-dkist-granulation-firstlight.jpg', kind='closeup', body='The Sun', cap=4000,
         credit='NSO/NSF/AURA', licence='CC BY 4.0', source='https://nso.edu/telescopes/dkist/first-light-full-image/',
         caption='Granules the size of Texas · Inouye Solar Telescope, 2019'),
    # Mercury
    dict(name='mercury-colour', src='inner/mercury-disc-messenger-enhanced-prockter07.jpg', kind='disc', body='Mercury',
         credit='NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington', licence='Public domain',
         source='https://commons.wikimedia.org/wiki/File:Mercury_in_color_-_Prockter07_centered.jpg', caption='MESSENGER, 2008 · enhanced colour'),
    dict(name='mercury-flyby', src='inner/mercury-disc-messenger-flyby1-pia13840.jpg', kind='disc', body='Mercury', at=(0.17, 0.40),
         credit='NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA13840', caption='MESSENGER, 2008'),
    dict(name='mercury-caloris', src='inner/mercury-closeup-messenger-caloris-pia13675.jpg', kind='closeup', body='Mercury', at=(0.45, 0.5),
         credit='NASA/Johns Hopkins University Applied Physics Laboratory/Carnegie Institution of Washington', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA13675', caption='The Caloris basin · MESSENGER, 2008'),
    # Venus
    dict(name='venus-radar', src='inner/venus-disc-magellan-radar-pia00104.tif', kind='disc', body='Venus',
         credit='NASA/JPL', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00104',
         caption='The surface under the clouds · Magellan radar, 1990–94, in the colours Venera saw'),
    dict(name='venus-akatsuki', src='inner/venus-disc-akatsuki-uvi-mccaughrean.png', kind='disc', body='Venus', crop=(0, 0, 1, 0.75), shrink=0.7,
         credit='JAXA/ISAS Akatsuki UVI; processing by Mark McCaughrean', licence='CC BY-SA 4.0',
         source='https://www.flickr.com/photos/markmccaughrean/54444410132/', caption='The clouds · Akatsuki · ultraviolet'),
    dict(name='venus-mariner', src='inner/venus-disc-mariner10-1974-mosaic.jpg', kind='disc', body='Venus',
         credit='NASA/JPL', licence='Public domain', source='https://www.flickr.com/photos/nasacommons/7544560662/',
         caption='The clouds · Mariner 10, 1974 · ultraviolet'),
    dict(name='venus-north', src='inner/venus-disc-magellan-radar-north-pia00271.tif', kind='disc', body='Venus', at=(0.48, 0.62),
         credit='NASA/JPL', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00271',
         caption='The north pole and Maxwell Montes · Magellan radar, 1990–94'),
    dict(name='venus-clouds', src='inner/venus-disc-mariner10-pia23791.tif', kind='disc', body='Venus', crop=(0.52, 0, 1, 1),
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA23791',
         caption='Mariner 10, 1974 · contrast enhanced'),
    # Earth
    dict(name='earth-marble', src='inner/earth-disc-apollo17-bluemarble-as17-148-22727.jpg', kind='disc', body='Earth', at=(0.57, 0.43),
         credit='NASA/Apollo 17 crew', licence='Public domain', source='https://commons.wikimedia.org/wiki/File:The_Blue_Marble,_AS17-148-22727.jpg',
         caption='The Blue Marble · Apollo 17, 1972'),
    dict(name='earth-nile', src='inner/earth-closeup-iss035-nile-sinai.jpg', kind='closeup', body='Earth', at=(0.55, 0.5),
         credit='ISS Expedition 35 crew, NASA Johnson Space Center', licence='Public domain',
         source='https://commons.wikimedia.org/wiki/File:ISS035-E-007148_Nile_-_Sinai_-_Dead_Sea_-_Wide_Angle_View.jpg',
         caption='The Nile, Sinai and the Red Sea · International Space Station, 2013'),
    dict(name='earth-africa', src='inner/earth-disc-dscovr-epic-africa-20240621.png', kind='disc', body='Earth',
         credit='NASA EPIC Team', licence='Public domain', source='https://epic.gsfc.nasa.gov/?date=2024-06-21',
         caption='Africa and Europe · DSCOVR, 21 June 2024'),
    dict(name='earth-glint', src='inner/earth-closeup-iss-cloudscape-philippine-sea.jpg', kind='closeup', body='Earth', at=(0.55, 0.65),
         credit='NASA', licence='Public domain', source='https://commons.wikimedia.org/wiki/File:Cloudscape_Over_the_Philippine_Sea.jpg',
         caption='Clouds over the Philippine Sea · International Space Station'),
    dict(name='earth-storms', src='inner/earth-closeup-iss020-thunderstorms-brazil.jpg', kind='closeup', body='Earth', at=(0.75, 0.6),
         credit='NASA Expedition 20 crew, NASA Earth Observatory', licence='Public domain',
         source='https://commons.wikimedia.org/wiki/File:ISS-20_Thunderstorms_on_the_Brazilian_Horizon.jpg',
         caption='Thunderstorms over Brazil · International Space Station, 2009'),
    dict(name='earth-aurora', src='inner/earth-closeup-aurora-iss073e0247726.jpg', kind='closeup', body='Earth', crop=(0, 0, 1, 0.78),
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/iss073e0247726',
         caption='The southern lights over the Indian Ocean · International Space Station, 2025'),
    dict(name='earth-clouds', src='inner/earth-closeup-iss034-stratocumulus.jpg', kind='closeup', body='Earth',
         credit='ISS Expedition 34 crew, NASA Johnson Space Center', licence='Public domain',
         source='https://commons.wikimedia.org/wiki/File:ISS034E016601_-_Stratocumulus_Clouds_-_Pacific_Ocean.jpg',
         caption='Stratocumulus over the Pacific · International Space Station'),
    dict(name='earth-americas', src='inner/earth-disc-dscovr-epic-americas-20240621.png', kind='disc', body='Earth',
         credit='NASA EPIC Team', licence='Public domain', source='https://epic.gsfc.nasa.gov/?date=2024-06-21',
         caption='The Americas · DSCOVR, 21 June 2024'),
    dict(name='earth-hawaii', src='inner/earth-closeup-iss038-hawaii.jpg', kind='closeup', body='Earth', at=(0.78, 0.82),
         credit='NASA', licence='Public domain', source='https://commons.wikimedia.org/wiki/File:ISS-38_Hawaiian_Island_chain.jpg',
         caption='The Hawaiian Islands · International Space Station'),
    dict(name='earth-night', src='inner/earth-closeup-iss046-india-night.jpg', kind='closeup', body='Earth',
         credit='NASA', licence='Public domain', source='https://commons.wikimedia.org/wiki/File:ISS-46_Northern_India_at_night.jpg',
         caption='Northern India at night · International Space Station'),
    # The Moon
    dict(kind='live', body='The Moon', credit="NASA's CGI Moon Kit: LRO's LROC colour and LOLA heights",
         licence='Public domain', source='https://svs.gsfc.nasa.gov/4720', caption='Right now, from where you are'),
    dict(name='moon-farside', src='inner/moon-disc-artemis2-farside-full-art002e009276.jpg', kind='disc', body='The Moon', at=(0.45, 0.65),
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e009276',
         caption='Orientale basin, where the near side meets the far · Artemis II, 2026'),
    dict(name='moon-limb', src='inner/moon-closeup-artemis2-limb-craters-art002e010399.jpg', kind='closeup', body='The Moon',
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e010399',
         caption='Ancient craters · Artemis II, 2026'),
    dict(name='moon-orientale', feather=0.06, src='inner/moon-disc-artemis2-orientale-art002e012183.jpg', kind='disc', body='The Moon', at=(0.30, 0.78),
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e012183',
         caption='Orientale basin and Grimaldi crater · Artemis II, 2026'),
    dict(name='moon-terminator', src='inner/moon-closeup-artemis2-terminator-art002e009281.jpg', kind='closeup', body='The Moon',
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e009281',
         caption='Long shadows at the edge of lunar day · Artemis II, 2026'),
    dict(name='moon-king', src='inner/moon-closeup-apollo16-king-crater-as16-120-19228.jpg', kind='closeup', body='The Moon',
         credit='NASA/Johnson Space Center', licence='Public domain', source='https://images.nasa.gov/details/as16-120-19228',
         caption='North of King crater, on the far side · Apollo 16, 1972'),
    dict(name='moon-vavilov', src='inner/moon-closeup-artemis2-vavilov-art002e009282.jpg', kind='closeup', body='The Moon',
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e009282',
         caption='Vavilov crater, on the rim of the Hertzsprung basin · Artemis II, 2026'),
    dict(name='moon-rings', src='inner/moon-closeup-artemis2-orientale-rings-art002e012090.jpg', kind='closeup', body='The Moon',
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e012090',
         caption='The rings of Orientale basin · Artemis II, 2026'),
    dict(name='moon-gibbous', src='inner/moon-disc-artemis2-gibbous-art002e009627.jpg', kind='disc', body='The Moon',
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e009627',
         caption='Artemis II, 2026'),
    dict(name='moon-aristarchus', src='inner/moon-closeup-artemis2-rays-limb-art002e012114.jpg', kind='closeup', body='The Moon',
         credit='NASA', licence='Public domain', source='https://images.nasa.gov/details/art002e012114',
         caption='Aristarchus crater and the Marius Hills · Artemis II, 2026'),
    # Mars
    dict(name='mars-viking', src='mars/mars-disc-viking-valles-usgs-enhanced.jpg', kind='disc', body='Mars', at=(0.55, 0.5),
         credit='NASA/JPL-Caltech/USGS', licence='Public domain',
         source='https://commons.wikimedia.org/wiki/File:PlanetMars-VallesMarineris-VikingOrbiter-1980.jpg',
         caption='Valles Marineris · Viking orbiters, 1976–80 · enhanced colour'),
    dict(name='mars-olympus', src='mars/mars-limb-hrsc-cloudy-tharsis-olympus-luck.jpg', kind='closeup', body='Mars', at=(0.72, 0.72), shrink=0.75,
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 4.0', source='https://www.flickr.com/photos/192271236@N03/55289692970',
         caption='Olympus Mons and the Tharsis volcanoes under cloud · Mars Express'),
    dict(name='mars-hebes', src='mars/mars-closeup-hrsc-hebes-chasma-falsecolour.tif', kind='closeup', body='Mars', crop=(0, 0, 1, 0.97), at=(0.45, 0.5),
         credit='ESA/DLR/FU Berlin (G. Neukum)', licence='CC BY-SA 3.0 IGO',
         source='https://www.esa.int/ESA_Multimedia/Images/2008/03/Hebes_Chasma_false-colour_nadir_view', caption='Hebes Chasma · Mars Express · false colour'),
    dict(name='mars-dunes', src='mars/mars-closeup-hirise-snowy-dunes-ESP_050703_2560.tif', kind='closeup', body='Mars',
         credit='NASA/JPL-Caltech/University of Arizona', licence='Public domain', source='https://www.uahirise.org/ESP_050703_2560',
         caption='Frosted dunes in the far north · Mars Reconnaissance Orbiter · enhanced colour'),
    dict(name='mars-express', saturation=0.7, src='mars/mars-disc-hrsc-tharsis-valles.png', kind='disc', body='Mars', at=(0.6, 0.55),
         credit='ESA/DLR/FU Berlin', licence='CC BY-SA 3.0 IGO', source='https://hrscteam.dlr.de/public/data/globalcolor.php',
         caption="Tharsis and Valles Marineris, from Mars Express's global mosaic · enhanced colour"),
    dict(name='mars-nicholson', src='mars/mars-closeup-hrsc-nicholson-crater.jpg', kind='closeup', body='Mars', crop=(0, 0, 1, 0.96), at=(0.5, 0.55),
         credit='ESA/DLR/FU Berlin (G. Neukum)', licence='CC BY-SA 3.0 IGO',
         source='https://commons.wikimedia.org/wiki/File:Colour_nadir_view_of_Nicholson_Crater_ESA233625.jpg', caption='Nicholson crater · Mars Express'),
    dict(name='mars-phobos', src='mars/mars-limb-hrsc-phobos-over-tharsis-luck.jpg', kind='closeup', body='Mars', crop=(0, 0, 0.975, 1), at=(0.84, 0.78), shrink=0.65,
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 2.0', source='https://www.flickr.com/photos/192271236@N03/53618430652',
         caption='Phobos over the Tharsis volcanoes · Mars Express'),
    dict(name='mars-north', src='mars/mars-closeup-hrsc-north-polar-korolev-luck.png', kind='closeup', body='Mars', at=(0.5, 0.4),
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 2.0', source='https://www.flickr.com/photos/192271236@N03/52876607762',
         caption='The north polar cap · Mars Express'),
    dict(name='mars-schiaparelli', src='mars/mars-disc-viking-schiaparelli-usgs-enhanced.jpg', kind='disc', body='Mars', at=(0.4, 0.45),
         credit='NASA/JPL-Caltech/USGS', licence='Public domain', source='https://commons.wikimedia.org/wiki/File:Schiaparelli_Hemisphere_Enhanced.jpg',
         caption='The Schiaparelli hemisphere · Viking orbiters · enhanced colour'),
    dict(name='mars-korolev', src='mars/mars-closeup-hrsc-korolev-plan.tif', kind='closeup', body='Mars', crop=(0, 0.03, 1, 0.92),
         credit='ESA/DLR/FU Berlin', licence='CC BY-SA 3.0 IGO', source='https://www.esa.int/ESA_Multimedia/Images/2018/12/Plan_view_of_Korolev_crater',
         caption='Korolev crater, full of ice · Mars Express, 2018'),
    dict(name='mars-defrost', src='mars/mars-closeup-hirise-icy-dune-ESP_017043_2640.tif', kind='closeup', body='Mars',
         credit='NASA/JPL-Caltech/University of Arizona', licence='Public domain', source='https://www.uahirise.org/ESP_017043_2640',
         caption='Dunes defrosting in spring · Mars Reconnaissance Orbiter · enhanced colour'),
    dict(name='mars-argyre', src='mars/mars-closeup-hrsc-argyre-luck.png', kind='closeup', body='Mars', crop=(0, 0.25, 1, 0.78), at=(0.5, 0.45),
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 2.0', source='https://www.flickr.com/photos/192271236@N03/53504991378',
         caption='Frost in the Argyre basin · Mars Express'),
    dict(name='mars-valles', src='mars/mars-closeup-viking-valles-mosaic-PIA00003.tif', kind='closeup', body='Mars', crop=(0.18, 0.35, 0.80, 0.76), at=(0.55, 0.58),
         credit='NASA/JPL/USGS', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00003',
         caption='Valles Marineris · Viking orbiters · enhanced colour'),
    dict(name='mars-clouds', src='mars/mars-limb-hrsc-clouds-terra-cimmeria-luck.jpg', kind='closeup', body='Mars', at=(0.8, 0.25),
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 4.0', source='https://www.flickr.com/photos/192271236@N03/55274343929',
         caption='Ice clouds over Terra Cimmeria · Mars Express'),
    dict(name='mars-syrtis', saturation=0.7, src='mars/mars-disc-hrsc-syrtis-hellas.png', kind='disc', body='Mars', at=(0.3, 0.4),
         credit='ESA/DLR/FU Berlin', licence='CC BY-SA 3.0 IGO', source='https://hrscteam.dlr.de/public/data/globalcolor.php',
         caption="Syrtis Major and Hellas, from Mars Express's global mosaic · enhanced colour"),
    dict(name='mars-south', src='mars/mars-closeup-hrsc-thyles-rupes-south-polar.tif', kind='closeup', body='Mars', crop=(0, 0, 1, 0.92), at=(0.48, 0.4),
         credit='ESA/DLR/FU Berlin', licence='CC BY-SA 3.0 IGO',
         source='https://www.esa.int/ESA_Multimedia/Images/2026/09/Raspberry_ripples_near_Mars_s_south_pole', caption='Frost near the south pole · Mars Express, 2026'),
    dict(name='mars-storm', src='mars/mars-closeup-hrsc-south-polar-duststorm-luck.png', kind='closeup', body='Mars', at=(0.55, 0.3), shrink=0.5,
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 4.0', source='https://www.flickr.com/photos/192271236@N03/55439640119',
         caption='A dust storm at the edge of the south polar cap · Mars Express · enhanced colour'),
    # Phobos, and the small worlds
    dict(name='phobos-mars', src='mars/phobos-over-mars-hrsc-limb-luck.jpg', kind='closeup', body='Phobos', at=(0.58, 0.55),
         credit='ESA/DLR/FU Berlin/Andrea Luck', licence='CC BY 2.0', source='https://www.flickr.com/photos/192271236@N03/52682839964',
         caption='Moon of Mars, with Mars behind · Mars Express · false colour'),
    dict(name='phobos-hirise', src='mars/phobos-disc-hirise-PIA10368.tif', kind='disc', body='Phobos', at=(0.88, 0.55),
         credit='NASA/JPL-Caltech/University of Arizona', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA10368',
         caption='Moon of Mars · Mars Reconnaissance Orbiter, 2008 · enhanced colour'),
    dict(name='ceres-dawn', src='mars/ceres-disc-dawn-occator-ortho-PIA21906.tif', kind='disc', body='Ceres', at=(0.5, 0.48), cap=4000, zoom=1.6,
         credit='NASA/JPL-Caltech/UCLA/MPS/DLR/IDA', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21906',
         caption="Dwarf planet in the asteroid belt, with Occator's bright spots · Dawn"),
    dict(name='bennu-osirisrex', src='mars/bennu-disc-polycam-mosaic-24km.jpg', kind='disc', body='Bennu',
         credit='NASA/Goddard/University of Arizona', licence='Public domain', source='https://commons.wikimedia.org/wiki/File:Bennu_mosaic_OSIRIS-REx.jpg',
         caption='Asteroid · OSIRIS-REx, 2018'),
    dict(name='ryugu-hayabusa2', src='mars/ryugu-disc-onc-20180911.png', kind='disc', body='Ryugu',
         credit='JAXA, University of Tokyo, Kochi University, Rikkyo University, Nagoya University, Chiba Institute of Technology, Meiji University, University of Aizu, AIST',
         licence='CC BY 4.0', source='https://commons.wikimedia.org/wiki/File:162173_Ryugu.png', caption='Asteroid · Hayabusa2, 2018'),
    dict(name='lutetia-rosetta', src='mars/lutetia-disc-osiris-pds.png', kind='disc', body='Lutetia',
         credit='ESA 2010 MPS for OSIRIS Team MPS/UPD/LAM/IAA/RSSD/INTA/UPM/DASP/IDA', licence='CC BY-SA 4.0',
         source='https://commons.wikimedia.org/wiki/File:21_Lutetia.png', caption='Asteroid · Rosetta, 2010'),
    # Jupiter
    dict(name='jupiter-hubble', src='jupiter/jupiter-disc-hubble-opal-2019.tif', kind='disc', body='Jupiter', at=(0.62, 0.55),
         credit='NASA, ESA, A. Simon (Goddard Space Flight Center) and M. H. Wong (University of California, Berkeley)', licence='CC BY 4.0',
         source='https://esahubble.org/images/heic1914a/', caption='Hubble, 2019'),
    dict(name='jupiter-marble', src='jupiter/jupiter-disc-juno-marble-pj18.tif', kind='disc', body='Jupiter', at=(0.68, 0.22),
         credit='NASA/JPL-Caltech/SwRI/MSSS, enhanced image by Kevin M. Gill', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA22946', caption='Juno, 2019 · enhanced colour'),
    dict(name='jupiter-belt', src='jupiter/jupiter-closeup-juno-neb-swift.tif', kind='closeup', body='Jupiter', at=(0.55, 0.40), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, image processing by Brian Swift', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA24972', caption='Clouds of the North Equatorial Belt · Juno, 2021 · enhanced colour'),
    dict(name='jupiter-cassini', src='jupiter/jupiter-disc-cassini-portrait-2000.tif', kind='disc', body='Jupiter', at=(0.52, 0.67),
         credit='NASA/JPL/Space Science Institute', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA04866', caption='Cassini, 2000'),
    dict(name='jupiter-grs', src='jupiter/jupiter-closeup-juno-grs-pj7-gill.tif', kind='closeup', body='Jupiter', crop=(0.075, 0, 0.925, 1), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, enhanced image by Kevin M. Gill', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA21395', caption='The Great Red Spot · Juno, 2017 · enhanced colour'),
    dict(name='jupiter-webb', src='jupiter/jupiter-disc-webb-nircam-2022.tif', kind='disc', body='Jupiter', at=(0.72, 0.72),
         credit='NASA, ESA, CSA, Jupiter ERS Team; image processing by Judy Schmidt', licence='CC BY 4.0',
         source='https://esawebb.org/images/jupiter-auroras1/', caption='Webb, 2022 · infrared'),
    dict(name='jupiter-shadow', src='jupiter/jupiter-closeup-juno-ganymede-shadow.tif', kind='closeup', body='Jupiter', crop=(0.03, 0, 0.97, 1), at=(0.15, 0.48), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, image processing by Thomas Thomopoulos', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA25015', caption="Ganymede's shadow · Juno, 2022 · enhanced colour"),
    dict(name='jupiter-horizon', src='jupiter/jupiter-closeup-juno-storm-horizon-pj21.tif', kind='closeup', body='Jupiter', crop=(0.02, 0, 0.98, 1), at=(0.83, 0.62), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, enhanced image by Kevin M. Gill', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA22950', caption='The Great Red Spot on the horizon · Juno, 2019 · enhanced colour'),
    dict(name='jupiter-north', src='jupiter/jupiter-closeup-juno-tumultuous.tif', kind='disc', body='Jupiter', at=(0.42, 0.33),
         credit='NASA/JPL-Caltech/SwRI/MSSS, enhanced image by Kevin M. Gill', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA22949', caption='The northern hemisphere · Juno, 2019 · enhanced colour'),
    dict(name='jupiter-swirls', src='jupiter/jupiter-closeup-juno-swirls-pj11.tif', kind='closeup', body='Jupiter', crop=(0.05, 0, 0.95, 1), at=(0.55, 0.45), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, enhanced image by Kevin M. Gill', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA21978', caption='The North Temperate Belt · Juno, 2018 · enhanced colour'),
    dict(name='jupiter-roses', src='jupiter/jupiter-closeup-juno-roses.tif', kind='closeup', body='Jupiter', crop=(0, 0, 1, 0.95), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, image processing by Rita Najm', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA24293', caption='Storms of the north · Juno, 2020 · enhanced colour'),
    dict(name='jupiter-stormy', src='jupiter/jupiter-closeup-juno-dark-stormy.tif', kind='closeup', body='Jupiter', crop=(0.05, 0, 0.95, 1), at=(0.5, 0.4), despeckle=0.12,
         credit='NASA/JPL-Caltech/SwRI/MSSS, enhanced image by Kevin M. Gill', licence='CC BY',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA22423', caption='Juno, 2018 · enhanced colour'),
    # Jupiter's moons
    dict(name='io-galileo', src='jupiter/io-disc-galileo-true.tif', kind='disc', body='Io', at=(0.33, 0.65),
         credit='NASA/JPL/University of Arizona', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA02308', caption='Moon of Jupiter · Galileo, 1999'),
    dict(name='io-mosaic', src='jupiter/io-disc-mosaic-zelario.png', kind='disc', body='Io',
         credit='zelario12, from NASA/JPL data', licence='CC BY-SA 4.0',
         source='https://www.flickr.com/photos/197038812@N04/53515582835', caption='Moon of Jupiter · Galileo and Voyager'),
    dict(name='europa-galileo', src='jupiter/europa-disc-galileo-reprocessed-2014.tif', kind='disc', body='Europa',
         credit='NASA/JPL-Caltech/SETI Institute', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA19048', caption='Moon of Jupiter · Galileo, late 1990s · enhanced colour'),
    dict(name='europa-juno', src='jupiter/europa-disc-juno-pj45-gill.png', kind='disc', body='Europa',
         credit='NASA/JPL-Caltech/SwRI/MSSS/Kevin M. Gill', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/kevinmgill/53255790801', caption='Moon of Jupiter · Juno, 2022'),
    dict(name='europa-limb', src='jupiter/europa-disc-juno-pj45-luck.png', kind='closeup', body='Europa', crop=(0, 0.03, 1, 1), at=(0.5, 0.65),
         credit='NASA/JPL-Caltech/SwRI/MSSS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/52401392707', caption='Moon of Jupiter · Juno, 2022 · enhanced colour'),
    dict(name='ganymede-juno', src='jupiter/ganymede-disc-juno-pj34-gill.png', kind='disc', body='Ganymede', at=(0.70, 0.35),
         credit='NASA/JPL-Caltech/SwRI/MSSS/Kevin M. Gill', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/kevinmgill/51237058399', caption='Moon of Jupiter · Juno, 2021'),
    dict(name='callisto-voyager', src='jupiter/callisto-disc-voyager2-cowart.png', kind='disc', body='Callisto',
         credit='NASA/JPL/Justin Cowart', licence='CC BY 2.0',
         source='https://commons.wikimedia.org/wiki/File:Callisto_-_Voyager_2_(26602921414).png', caption='Moon of Jupiter · Voyager 2, 1979'),
    # Saturn
    dict(name='saturn-jewel', src='saturn/saturn-disc-cassini-PIA17474.tif', kind='disc', body='Saturn', at=(0.52, 0.32),
         credit='NASA/JPL-Caltech/Space Science Institute/Cornell', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA17474',
         caption='From high above, with the hexagon at the pole · Cassini, 2013'),
    dict(name='saturn-portrait', src='saturn/saturn-disc-cassini-PIA06193.tif', kind='disc', body='Saturn', at=(0.2, 0.45), cap=4800, zoom=1.5,
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA06193',
         caption='Cassini, 2004'),
    dict(name='saturn-eclipse', src='saturn/saturn-backlit-cassini-PIA14934.tif', kind='disc', body='Saturn', cap=4800,
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA14934',
         caption='In Saturn\'s shadow, lit from behind · Cassini, 2012 · enhanced colour'),
    dict(name='saturn-shadows', src='saturn/saturn-crescent-high-cassini-PIA08388.tif', kind='disc', body='Saturn', at=(0.4, 0.45),
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA08388',
         caption='Ring shadows, from above the unlit side · Cassini, 2007'),
    dict(name='saturn-equinox', src='saturn/saturn-equinox-cassini-PIA11667.tif', kind='disc', body='Saturn', at=(0.47, 0.45),
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA11667',
         caption='Equinox · Cassini, 2009'),
    dict(name='saturn-farewell', src='saturn/saturn-disc-brightened-cassini-PIA17218fig1.jpg', kind='disc', body='Saturn', cap=4000,
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA17218',
         caption="Cassini's farewell, 2017"),
    dict(name='saturn-rings', src='saturn/saturn-rings-from-above-cassini-PIA08361.tif', kind='disc', body='Saturn',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA08361',
         caption='The rings from high above · Cassini, 2007'),
    dict(name='saturn-2008', src='saturn/saturn-disc-cassini-PIA11141.tif', kind='disc', body='Saturn',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA11141',
         caption='Cassini, 2008'),
    dict(name='saturn-far', src='saturn/saturn-disc-cassini-PIA21345.tif', kind='disc', body='Saturn',
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21345',
         caption='One of its last looks from afar · Cassini, 2016'),
    # Saturn's moons, inside out
    dict(name='mimas-cassini', src='saturn/mimas-disc-herschel-cassini-PIA12569.tif', kind='disc', body='Mimas', at=(0.28, 0.42), shrink=0.6,
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA12569',
         caption='Moon of Saturn, with Herschel crater · Cassini, 2010'),
    dict(name='enceladus-gill', src='saturn/enceladus-disc-gill-20050717.jpg', kind='disc', body='Enceladus', at=(0.35, 0.85),
         credit='NASA/JPL-Caltech/Space Science Institute/Kevin M. Gill', licence='CC BY 2.0', source='https://www.flickr.com/photos/kevinmgill/22361058118/',
         caption='Moon of Saturn · Cassini, 2005 · false colour'),
    dict(name='enceladus-crescent', src='saturn/enceladus-crescent-cassini-PIA11133.tif', kind='disc', body='Enceladus',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA11133',
         caption='Moon of Saturn · Cassini, 2008 · enhanced colour'),
    dict(name='enceladus-stripes', src='saturn/enceladus-closeup-tigerstripes-cassini-PIA11135.tif', kind='closeup', body='Enceladus',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA11135',
         caption='The tiger stripes, where its geysers rise · Cassini, 2008'),
    dict(name='tethys-colour', src='saturn/tethys-disc-color-cassini-PIA19636.tif', kind='disc', body='Tethys',
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19636',
         caption='Moon of Saturn · Cassini, 2015 · enhanced colour'),
    dict(name='tethys-cassini', src='saturn/tethys-disc-cassini-PIA07738.tif', kind='disc', body='Tethys',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA07738',
         caption='Moon of Saturn · Cassini, 2005'),
    dict(name='dione-rings', src='saturn/dione-disc-rings-cassini-PIA19650.tif', kind='closeup', body='Dione',
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19650',
         caption="Moon of Saturn, before Saturn's rings · Cassini, 2015"),
    dict(name='rhea-colour', src='saturn/rhea-disc-color-cassini-PIA19057.tif', kind='disc', body='Rhea', crop=(0.5, 0, 1, 1),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19057',
         caption='Moon of Saturn · Cassini, 2015 · enhanced colour'),
    dict(name='rhea-cassini', src='saturn/rhea-disc-cassini-PIA07763.tif', kind='disc', body='Rhea',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA07763',
         caption='Moon of Saturn · Cassini, 2005'),
    dict(name='titan-dione', src='titan/PIA14910.tif', kind='disc', body='Titan', keepblack=True, box=(0, 0, 1, 1), margin=0, vignette=0.45, at=(0.5, 0.5),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA14910',
         caption='Moon of Saturn, with Dione, before Saturn and its rings · Cassini, 2011'),
    dict(name='titan-rings', src='saturn/titan-disc-rings-cassini-PIA14909.tif', kind='disc', body='Titan', keepblack=True, box=(0, 0, 1, 1), margin=0, vignette=0.45,
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA14909',
         caption="Moon of Saturn, before the rings and Saturn · Cassini, 2011"),
    dict(name='titan-surface', src='saturn/titan-globes-vims-PIA21923.tif', kind='disc', body='Titan', crop=(0.35, 0.5, 0.65, 1),
         credit='NASA/JPL-Caltech/University of Nantes/University of Arizona', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21923',
         caption='The surface under the haze · Cassini, 2004–17 · infrared'),
    dict(name='titan-candle', src='titan/PIA08235.tif', kind='disc', body='Titan', box=(0, 0, 1, 1), margin=0, feather=0.08, at=(0.5, 0.45),
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA08235',
         caption='Its haze lit from behind, with Enceladus and the rings · Cassini, 2006'),
    dict(name='titan-layers', src='titan/PIA19642.tif', kind='disc', body='Titan', keepblack=True, box=(0, 0, 1, 1), margin=0, vignette=0.45,
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19642',
         caption='Its surface through the haze, before Saturn and its rings · Cassini, 2012 · near infrared'),
    dict(name='titan-rhea', src='titan/PIA21904.tif', kind='disc', body='Titan', box=(0, 0, 1, 1), margin=0.03,
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21904',
         caption='Rhea passing in front · Cassini, 2009'),
    dict(name='titan-saturn', src='titan/PIA18335.tif', kind='disc', body='Titan', keepblack=True, box=(0, 0, 1, 1), margin=0, vignette=0.45, at=(0.77, 0.72),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA18335',
         caption='Two veiled worlds: Titan before Saturn · Cassini, 2015'),
    dict(name='titan-haze', src='saturn/titan-haze-ring-cassini-PIA12606.tif', kind='disc', body='Titan',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA12606',
         caption='Its haze lit from behind · Cassini'),
    dict(name='hyperion-gill', src='saturn/hyperion-disc-gill-200509.jpg', kind='disc', body='Hyperion', shrink=0.6,
         credit='NASA/JPL/Space Science Institute, processed by Kevin M. Gill', licence='CC BY 2.0', source='https://www.flickr.com/photos/kevinmgill/16744503449/',
         caption='Moon of Saturn · Cassini, 2005 · false colour'),
    dict(name='hyperion-cassini', src='saturn/hyperion-disc-cassini-PIA07740.tif', kind='disc', body='Hyperion',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA07740',
         caption='Moon of Saturn · Cassini, 2005 · false colour'),
    dict(name='iapetus-cassini', src='saturn/iapetus-disc-cassini-PIA08384.tif', kind='disc', body='Iapetus',
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA08384',
         caption='Moon of Saturn, half dark and half bright · Cassini, 2007 · false colour'),
    dict(name='iapetus-ridge', src='saturn/iapetus-crescent-ridge-cassini-PIA08376.tif', kind='disc', body='Iapetus', at=(0.12, 0.5),
         credit='NASA/JPL/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA08376',
         caption='Its equatorial ridge on the edge · Cassini, 2007 · false colour'),
    dict(name='phoebe-cassini', src='saturn/phoebe-disc-cassini-PIA18411.tif', kind='disc', body='Phoebe', crop=(0, 0, 0.5, 1),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA18411',
         caption='Moon of Saturn · Cassini, 2004'),
    dict(name='pan-cassini', src='saturn/atlas-daphnis-pan-cassini-PIA21449.tif', kind='disc', body='Pan', crop=(0.05, 0.6, 0.95, 1),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21449',
         caption='Moon of Saturn, 35 km across · Cassini, 2017 · enhanced colour'),
    dict(name='daphnis-cassini', src='saturn/daphnis-keeler-gap-cassini-PIA21056.tif', kind='disc', body='Daphnis', keepblack=True, box=(0, 0, 1, 1), margin=0, vignette=0.45, at=(0.64, 0.74),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21056',
         caption='Moon of Saturn, making waves in the Keeler gap · Cassini, 2017'),
    dict(name='atlas-cassini', src='saturn/atlas-daphnis-pan-cassini-PIA21449.tif', kind='disc', body='Atlas', crop=(0.05, 0, 0.95, 0.42),
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21449',
         caption='Moon of Saturn · Cassini, 2017 · enhanced colour'),
    dict(name='helene-cassini', src='saturn/helene-cassini-PIA12773.tif', kind='disc', body='Helene',
         credit='NASA/JPL-Caltech/Space Science Institute', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA12773',
         caption='Moon of Saturn · Cassini, 2011'),
    # Uranus
    dict(name='uranus-webb', src='outer/uranus-rings-webb-weic2602a.tif', kind='disc', body='Uranus', at=(0.45, 0.35),
         credit='ESA/Webb, NASA, CSA, STScI, P. Tiranti, H. Melin, M. Zamani (ESA/Webb)', licence='CC BY 4.0',
         source='https://esawebb.org/images/weic2602a/', caption='Its rings and aurora · Webb, 2026 · infrared'),
    dict(name='uranus-voyager', src='outer/uranus-disc-voyager-PIA18182.tif', kind='disc', body='Uranus',
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA18182',
         caption='Voyager 2, 1986'),
    dict(name='uranus-crescent', src='outer/uranus-crescent-voyager-luck.png', kind='disc', body='Uranus', crop=(0.025, 0, 1, 1),
         credit='NASA/JPL-Caltech/Voyager-ISS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/52523609952', caption='Leaving Uranus · Voyager 2, 1986'),
    dict(name='uranus-rings', src='outer/uranus-rings-webb-weic2310a.tif', kind='disc', body='Uranus',
         credit='NASA, ESA, CSA, STScI, J. DePasquale (STScI)', licence='CC BY 4.0',
         source='https://esawebb.org/images/weic2310a/', caption='Webb, 2023 · infrared'),
    dict(name='miranda-voyager', src='outer/miranda-disc-voyager-zelario.png', kind='disc', body='Miranda', at=(0.45, 0.5),
         credit='NASA/JPL-Caltech, processed by zelario12', licence='CC BY-SA 2.0',
         source='https://www.flickr.com/photos/197038812@N04/53467048107', caption='Moon of Uranus · Voyager 2, 1986'),
    dict(name='miranda-south', src='outer/miranda-disc-voyager-PIA01490.tif', kind='disc', body='Miranda',
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA01490',
         caption='Moon of Uranus · Voyager 2, 1986'),
    dict(name='ariel-voyager', src='outer/ariel-disc-voyager-PIA01534.tif', kind='disc', body='Ariel', at=(0.55, 0.5),
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA01534',
         caption='Moon of Uranus · Voyager 2, 1986'),
    dict(name='umbriel-voyager', src='outer/umbriel-disc-voyager-PIA00040.tif', kind='disc', body='Umbriel',
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00040',
         caption='Moon of Uranus · Voyager 2, 1986'),
    dict(name='titania-voyager', src='outer/titania-disc-voyager-gill.jpg', kind='disc', body='Titania',
         credit='NASA/JPL-Caltech/Kevin M. Gill', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/53460575@N03/31492575221', caption='Moon of Uranus · Voyager 2, 1986'),
    dict(name='titania-colour', src='outer/titania-disc-voyager-PIA00036.tif', kind='disc', body='Titania',
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00036',
         caption='Moon of Uranus · Voyager 2, 1986'),
    dict(name='oberon-voyager', src='outer/oberon-disc-voyager-PIA00034.tif', kind='disc', body='Oberon',
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00034',
         caption='Moon of Uranus · Voyager 2, 1986'),
    # Neptune
    dict(name='neptune-voyager', src='outer/neptune-disc-voyager-luck-52494377269.png', kind='disc', body='Neptune', at=(0.40, 0.45),
         credit='NASA/JPL-Caltech/Voyager-ISS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/52494377269', caption='The Great Dark Spot · Voyager 2, 1989 · enhanced colour'),
    dict(name='neptune-true', src='outer/neptune-disc-truecolour-voyager-luck-53506151058.png', kind='disc', body='Neptune', crop=(0.02, 0, 1, 1), at=(0.38, 0.40),
         credit='NASA/JPL-Caltech/Voyager-ISS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/53506151058', caption='Voyager 2, 1989'),
    dict(name='neptune-clouds', src='outer/neptune-closeup-clouds-voyager-luck.png', kind='closeup', body='Neptune', crop=(0, 0, 1, 0.965), at=(0.7, 0.25), shrink=0.6,
         credit='NASA/JPL-Caltech/Voyager-ISS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/51599930794', caption='High cirrus · Voyager 2, 1989'),
    dict(name='neptune-other', src='outer/neptune-disc-voyager-luck-51932458995.png', kind='disc', body='Neptune', crop=(0.05, 0, 1, 0.93),
         credit='NASA/JPL-Caltech/Voyager-ISS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/51932458995', caption='Voyager 2, 1989 · enhanced colour'),
    dict(name='neptune-crescent', src='outer/neptune-crescent-triton-voyager-luck.png', kind='disc', body='Neptune', box=(0.12, 0.1, 0.88, 0.92),
         credit='NASA/JPL-Caltech/Voyager-ISS/Andrea Luck', licence='CC BY 2.0',
         source='https://www.flickr.com/photos/192271236@N03/51935821827', caption='Neptune and Triton, leaving · Voyager 2, 1989'),
    dict(name='neptune-south', src='outer/neptune-crescent-southpole-voyager-PIA01539.tif', kind='disc', body='Neptune', crop=(0.01, 0.01, 0.99, 0.98),
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA01539',
         caption='Leaving Neptune · Voyager 2, 1989'),
    dict(name='triton-voyager', feather=0.05, src='outer/triton-disc-voyager-PIA00317.tif', kind='disc', body='Triton', at=(0.45, 0.75), shrink=0.7,
         credit='NASA/JPL/USGS', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00317',
         caption='Moon of Neptune · Voyager 2, 1989'),
    dict(name='proteus-voyager', src='outer/proteus-disc-voyager-PIA00062.tif', kind='disc', body='Proteus',
         credit='NASA/JPL-Caltech', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA00062',
         caption='Moon of Neptune · Voyager 2, 1989'),
    # Pluto and beyond
    dict(name='pluto-true', src='outer/pluto-disc-truecolour-nh-8000.png', kind='disc', body='Pluto', at=(0.65, 0.55),
         credit='NASA/JHUAPL/SwRI/Alex Parker', licence='Public domain',
         source='https://pluto.jhuapl.edu/Galleries/Featured-Images/image.php?gallery_id=2&image_id=543', caption='New Horizons, 2015'),
    dict(name='pluto-colour', src='outer/pluto-disc-enhanced-nh-PIA19952.tif', kind='disc', body='Pluto', at=(0.30, 0.60), cap=4000,
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19952',
         caption='New Horizons, 2015 · enhanced colour'),
    dict(name='pluto-haze', feather=0.06, src='outer/pluto-crescent-haze-nh-PIA20727.tif', kind='disc', body='Pluto', at=(0.55, 0.17),
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA20727',
         caption='Haze lit from behind · New Horizons, 2015'),
    dict(name='pluto-mountains', src='outer/pluto-closeup-mountains-haze-nh-PIA19948.tif', kind='closeup', body='Pluto', at=(0.35, 0.6),
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19948',
         caption='Mountains, ice plains and haze at sunset · New Horizons, 2015'),
    dict(name='pluto-blue', src='outer/pluto-crescent-bluehaze-nh-PIA21590.tif', kind='disc', body='Pluto',
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA21590',
         caption='Blue haze on departure · New Horizons, 2015'),
    dict(name='pluto-north', src='outer/pluto-closeup-northpole-nh-PIA20473.tif', kind='closeup', body='Pluto',
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA20473',
         caption='Canyons of the north pole · New Horizons, 2015 · enhanced colour'),
    dict(name='charon-colour', src='outer/charon-disc-enhanced-nh-PIA19968.tif', kind='disc', body='Charon', at=(0.5, 0.12),
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA19968',
         caption='Moon of Pluto · New Horizons, 2015 · enhanced colour'),
    dict(name='charon-true', src='outer/charon-disc-truecolour-nh.png', kind='disc', body='Charon',
         credit='NASA/JHUAPL/SwRI/Alex Parker', licence='Public domain',
         source='https://pluto.jhuapl.edu/Galleries/Featured-Images/image.php?gallery_id=2&image_id=544', caption='Moon of Pluto · New Horizons, 2015'),
    dict(name='nix-nh', src='outer/nix-disc-nh-PIA20287.tif', kind='disc', body='Nix', shrink=0.6,
         credit='NASA/JHUAPL/SwRI', licence='Public domain', source='https://photojournal.jpl.nasa.gov/catalog/PIA20287',
         caption='Moon of Pluto · New Horizons, 2015'),
    dict(name='arrokoth-nh', src='outer/arrokoth-enhanced-nh.png', kind='disc', body='Arrokoth', shrink=0.6,
         credit='NASA/JHUAPL/SwRI/Roman Tkachenko', licence='Public domain',
         source='https://pluto.jhuapl.edu/Galleries/Featured-Images/image.php?gallery_id=2&image_id=626',
         caption='In the Kuiper belt, 6.6 billion km out · New Horizons, 2019 · enhanced colour'),
    # Comet 67P
    dict(name='67p-jets', feather=0.06, src='mars/67p-whole-navcam-jets-2015-02-03.jpg', kind='disc', body='Comet 67P',
         credit='ESA/Rosetta/NAVCAM', licence='CC BY-SA 3.0 IGO', source='https://www.esa.int/ESA_Multimedia/Images/2015/02/Comet_on_3_February_2015_NavCam',
         caption='Churyumov–Gerasimenko, with its jets · Rosetta, 2015'),
    dict(name='67p-cliffs', src='mars/67p-closeup-navcam-cliffs-jets-2014-12-10.jpg', kind='disc', body='Comet 67P', keepblack=True, box=(0, 0, 1, 1), margin=0, vignette=0.45,
         credit='ESA/Rosetta/NAVCAM', licence='CC BY-SA 3.0 IGO', source='https://www.esa.int/ESA_Multimedia/Images/2014/12/Comet_on_10_December_2014_NavCam',
         caption='Cliffs and jets on Churyumov–Gerasimenko · Rosetta, 2014'),
]

# Mars from the ground, woven in among the views from orbit so a visit alternates between them.
MARS_SURFACE = [
    dict(name='mars-jezero', src='../surface/mars/mars-surface-perseverance-jezero-delta-2.5-gigapixel-PIA24921.jpg', kind='surface', body='Mars', quality=60,
         crop=(0.46, 0, 1, 0.763), at=(0.58, 0.10), credit='NASA/JPL-Caltech/ASU/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA24921', caption="The delta in Jezero crater · Perseverance, 2022 · enhanced colour"),
    dict(name='mars-gediz', src='../surface/mars/mars-surface-curiosity-heading-west-gediz-PIA26471.jpg', kind='surface', body='Mars', quality=60,
         crop=(0.015, 0.114, 0.352, 0.812), at=(0.27, 0.25), credit='NASA/JPL-Caltech/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA26471', caption="Leaving Gediz Vallis, on Mount Sharp · Curiosity, 2024" + " · colours as if under Earth's sky"),
    dict(name='mars-pinestand', src='../surface/mars/mars-surface-perseverance-pinestand-PIA25830.tif', kind='surface', body='Mars', quality=60,
         crop=(0, 0, 0.99, 0.909), at=(0.70, 0.30), credit='NASA/JPL-Caltech/ASU/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA25830', caption="The 'Pinestand' mound, on Jezero's delta · Perseverance, 2023"),
    dict(name='mars-paraitepuy', src='../surface/mars/mars-surface-curiosity-paraitepuy-pass-PIA25413.jpg', kind='surface', body='Mars', quality=60, split=3,
         crop=(0.131, 0.258, 0.94, 0.523), credit='NASA/JPL-Caltech/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA25413', caption="Paraitepuy Pass, between two buttes · Curiosity, 2022" + " · colours as if under Earth's sky"),
    dict(name='mars-falbreen', src='../surface/mars/mars-surface-perseverance-falbreen-PIA26644.jpg', kind='surface', body='Mars', quality=60,
         crop=(0.221, 0, 0.771, 0.745), credit='NASA/JPL-Caltech/ASU/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA26644', caption="'Falbreen', on the rim of Jezero crater · Perseverance, 2025 · enhanced colour"),
    dict(name='mars-santa-maria', src='../surface/mars/mars-surface-opportunity-santa-maria-PIA13794.tif', kind='surface', body='Mars', quality=60, split=2,
         crop=(0.083, 0.2, 0.9, 0.76), credit='NASA/JPL-Caltech/Cornell/ASU', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA13794', caption="Santa Maria crater · Opportunity, 2010"),
    dict(name='mars-husband-hill', src='../surface/mars/mars-surface-spirit-husband-hill-summit-PIA04184.tif', kind='surface', body='Mars', quality=60, split=3,
         crop=(0, 0, 1, 0.68), credit='NASA/JPL-Caltech/Cornell', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA04184', caption="From the summit of Husband Hill, over Gusev crater · Spirit, 2005"),
    dict(name='mars-bolivar', src='../surface/mars/mars-surface-curiosity-bolivar-sand-ridges-PIA25414.tif', kind='surface', body='Mars', quality=60,
         crop=(0.054, 0.209, 0.946, 0.852), at=(0.80, 0.35), credit='NASA/JPL-Caltech/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA25414', caption="Sand ridges and the 'Bolívar' butte · Curiosity, 2022" + " · colours as if under Earth's sky"),
    dict(name='mars-glen-torridon', src='../surface/mars/mars-surface-curiosity-glen-torridon-1.8-gigapixel-PIA23623.jpg', kind='surface', body='Mars', quality=60, split=2,
         crop=(0.005, 0.16, 0.579, 0.62), credit='NASA/JPL-Caltech/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA23623', caption="Glen Torridon, from the 1.8-billion-pixel panorama · Curiosity, 2019"),
    dict(name='mars-bright-angel', src='../surface/mars/mars-surface-perseverance-bright-angel-PIA26369.jpg', kind='surface', body='Mars', quality=60, split=3,
         crop=(0, 0, 0.8, 0.44), credit='NASA/JPL-Caltech/ASU/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA26369', caption="Around 'Bright Angel', in Neretva Vallis · Perseverance, 2024 · enhanced colour"),
    dict(name='mars-boulders', src='../surface/mars/mars-surface-perseverance-boulder-field-PIA25963.tif', kind='surface', body='Mars', quality=60,
         crop=(0.035, 0.041, 0.919, 0.981), at=(0.70, 0.85), credit='NASA/JPL-Caltech/ASU/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA25963', caption="A boulder field on top of Jezero's delta · Perseverance, 2023"),
    dict(name='mars-mount-sharp', src='../surface/mars/mars-surface-curiosity-dramatic-mount-sharp-PIA23898.tif', kind='surface', body='Mars', quality=60, split=2,
         crop=(0.263, 0.235, 0.749, 0.711), credit='NASA/JPL-Caltech/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA23898', caption="Mount Sharp and the Greenheugh pediment · Curiosity, 2019" + " · colours as if under Earth's sky"),
    dict(name='mars-texoli', src='../surface/mars/mars-surface-curiosity-texoli-PIA26477.tif', kind='surface', body='Mars', quality=60, split=2,
         crop=(0.199, 0.105, 0.554, 0.728), credit='NASA/JPL-Caltech/MSSS', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA26477', caption="The 'Texoli' butte · Curiosity, 2024" + " · colours as if under Earth's sky"),
    dict(name='mars-ingenuity', src='../surface/mars/mars-surface-ingenuity-castell-henllys-PIA25890.tif', kind='surface', body='Mars', quality=60,
         crop=(0.036, 0, 0.965, 1), credit='NASA/JPL-Caltech', licence='Public domain',
         source='https://photojournal.jpl.nasa.gov/catalog/PIA25890', caption="From the air, over 'Castell Henllys' · Ingenuity, 2023 · enhanced colour"),
]


def weave(photos, body, surface):
    """The body's views from orbit and from the ground, alternating, in place of its views from orbit."""
    own = [p for p in photos if p['body'] == body]
    at = photos.index(own[0])
    rest = [p for p in photos if p['body'] != body]
    woven = [p for pair in zip(own, surface) for p in pair] + own[len(surface):] + surface[len(own):]
    return rest[:at] + woven + rest[at:]


PHOTOS = weave(PHOTOS, 'Mars', MARS_SURFACE)

# The Moon and the small worlds from the ground, or the last moments before touching it.
O = '../surface/other/'
MOON_SURFACE = [
    dict(name='moon-apollo16', src=O + 'moon-pano-apollo16-young-rover-orion-flag-jsc2011e118363.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.52, 0.35), credit='NASA/Johnson Space Center', licence='Public domain', source='https://images.nasa.gov/details/jsc2011e118363',
         caption='John Young, the rover and the lander at Descartes · Apollo 16, 1972'),
    dict(name='moon-aldrin', src=O + 'moon-surface-apollo11-aldrin-AS11-40-5903.jpg', kind='surface', body='The Moon', quality=60,
         crop=(0, 0, 0.985, 1), at=(0.52, 0.15), credit='NASA / Project Apollo Archive', licence='Public domain',
         source='https://www.flickr.com/photos/projectapolloarchive/21039130393', caption='Buzz Aldrin at Tranquility Base · Apollo 11, 1969'),
    dict(name='moon-hadley-rille', src=O + 'moon-pano-apollo15-rover-hadley-rille-jsc2011e118359.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.47, 0.55), credit='NASA/Johnson Space Center', licence='Public domain', source='https://images.nasa.gov/details/jsc2011e118359',
         caption='David Scott and the rover at the rim of Hadley Rille · Apollo 15, 1971'),
    dict(name='moon-earth-flag', src=O + 'moon-surface-apollo17-schmitt-flag-earth-AS17-134-20384.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.60, 0.24), credit='NASA / Project Apollo Archive', licence='Public domain',
         source='https://www.flickr.com/photos/projectapolloarchive/21492224000', caption='Earth over the flag, with Harrison Schmitt · Apollo 17, 1972'),
    dict(name='moon-taurus-littrow', src=O + 'moon-pano-apollo17-rover-taurus-littrow-jsc2004e52775.jpg', kind='surface', body='The Moon', quality=60,
         split=2, credit='NASA/Johnson Space Center', licence='Public domain', source='https://images.nasa.gov/details/jsc2004e52775',
         caption='The valley of Taurus-Littrow · Apollo 17, 1972'),
    dict(name='moon-tracys-rock', src=O + 'moon-surface-apollo17-station6-tracys-rock-AS17-140-21497.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.27, 0.72), credit='NASA / Project Apollo Archive', licence='Public domain',
         source='https://www.flickr.com/photos/projectapolloarchive/21496389518', caption="Harrison Schmitt at the split boulder, Station 6 · Apollo 17, 1972"),
    dict(name='moon-little-west', src=O + 'moon-pano-apollo11-crater-eagle-jsc2008e040725.jpg', kind='surface', body='The Moon', quality=60,
         split=2, credit='NASA/Johnson Space Center', licence='Public domain', source='https://images.nasa.gov/details/jsc2008e040725',
         caption='Little West crater, with Eagle on the horizon · Apollo 11, 1969'),
    dict(name='moon-irwin', src=O + 'moon-surface-apollo15-irwin-salute-rover-AS15-88-11866.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.22, 0.50), credit='NASA / Project Apollo Archive', licence='Public domain',
         source='https://www.flickr.com/photos/projectapolloarchive/21648389932', caption='James Irwin salutes, below Hadley Delta · Apollo 15, 1971'),
    dict(name='moon-station8', src=O + 'moon-pano-apollo15-station8-mt-hadley-lm-jsc2011e118360.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.70, 0.45), credit='NASA/Johnson Space Center', licence='Public domain', source='https://images.nasa.gov/details/jsc2011e118360',
         caption='The lander Falcon under Mount Hadley · Apollo 15, 1971'),
    dict(name='moon-young-jump', src=O + 'moon-surface-apollo16-young-jump-salute-AS16-113-18339.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.62, 0.45), credit='NASA / Project Apollo Archive', licence='Public domain',
         source='https://www.flickr.com/photos/projectapolloarchive/21028582504', caption='John Young, mid-jump in a salute · Apollo 16, 1972'),
    dict(name='moon-surveyor-crater', src=O + 'moon-pano-apollo12-bean-intrepid-surveyor-crater-jsc2011e118358.jpg', kind='surface', body='The Moon',
         quality=60, at=(0.61, 0.58), credit='NASA/Johnson Space Center', licence='Public domain',
         source='https://images.nasa.gov/details/jsc2011e118358', caption='Alan Bean at the rim of Surveyor crater · Apollo 12, 1969'),
    dict(name='moon-mt-hadley', src=O + 'moon-surface-apollo15-mt-hadley-AS15-90-12187.jpg', kind='surface', body='The Moon', quality=60,
         credit='NASA / Project Apollo Archive', licence='Public domain', source='https://www.flickr.com/photos/projectapolloarchive/21501817950',
         caption='Mount Hadley · Apollo 15, 1971'),
    dict(name='moon-surveyor3', src=O + 'moon-surface-apollo12-surveyor3-intrepid-AS12-48-7133.jpg', kind='surface', body='The Moon', quality=60,
         at=(0.62, 0.38), credit='NASA / Project Apollo Archive', licence='Public domain',
         source='https://www.flickr.com/photos/projectapolloarchive/21470506269', caption='Pete Conrad at Surveyor 3, landed two years before · Apollo 12, 1969'),
]
OTHER_SURFACE = {
    'Titan': [dict(name='titan-huygens', src=O + 'titan-huygens-surface-first-colour-PIA07232.jpg', kind='surface', body='Titan', quality=70,
                   crop=(0.211, 0.046, 0.789, 0.952), feather=0.1, credit='NASA/JPL/ESA/University of Arizona', licence='Public domain',
                   source='https://photojournal.jpl.nasa.gov/catalog/PIA07232',
                   caption="The only photo from its surface; the pebbles are 4 to 15 cm · Huygens, 2005 · colours from its spectra")],
    'Bennu': [dict(name='bennu-tag', src=O + 'bennu-osirisrex-tag-contact-debris-samcam-20201020T214951.png', kind='surface', body='Bennu', quality=70,
                   vignette=0.35, credit='NASA/Goddard/University of Arizona', licence='Public domain',
                   source='https://sbnarchive.psi.edu/pds4/orex/orex.ocams/', caption='The moment OSIRIS-REx grabbed its sample · 2020'),
              dict(name='bennu-before', src=O + 'bennu-osirisrex-tag-before-contact-samcam-20201020T214944.png', kind='surface', body='Bennu', quality=70,
                   vignette=0.35, credit='NASA/Goddard/University of Arizona', licence='Public domain',
                   source='https://sbnarchive.psi.edu/pds4/orex/orex.ocams/', caption='Seconds before touching down · OSIRIS-REx, 2020')],
    'Ryugu': [dict(name='ryugu-horizon', src=O + 'ryugu-hayabusa2-td2-horizon-onc-w2-20190711T010457.png', kind='surface', body='Ryugu', quality=70,
                   crop=(0, 0, 1, 0.99), vignette=0.3, credit='ISAS/JAXA (contrast stretched)', licence='Japanese Government Standard Terms of Use 2.0',
                   source='https://darts.isas.jaxa.jp/pub/hayabusa2/onc_bundle/', caption='Boulders to the horizon, touching down · Hayabusa2, 2019'),
              dict(name='ryugu-shadow', src=O + 'ryugu-hayabusa2-td1-after-touchdown-shadow-onc-w1-20190221T222957.png', kind='surface', body='Ryugu',
                   quality=70, vignette=0.3, credit='ISAS/JAXA (contrast stretched)', licence='Japanese Government Standard Terms of Use 2.0',
                   source='https://darts.isas.jaxa.jp/pub/hayabusa2/onc_bundle/', caption="Hayabusa2's shadow, rising after its first touchdown · 2019"),
              dict(name='ryugu-approach', src=O + 'ryugu-hayabusa2-td1-shadow-approach-onc-w1-20190221T222828.png', kind='surface', body='Ryugu',
                   quality=70, vignette=0.3, credit='ISAS/JAXA (contrast stretched)', licence='Japanese Government Standard Terms of Use 2.0',
                   source='https://darts.isas.jaxa.jp/pub/hayabusa2/onc_bundle/', caption="Hayabusa2's shadow, coming down · 2019")],
    'Comet 67P': [dict(name='67p-maat', src=O + 'comet67p-rosetta-descent-maat-pit-osiris-nac-N20160930T092653.png', kind='surface', body='Comet 67P',
                       quality=70, credit='ESA/Rosetta/MPS for OSIRIS Team MPS/UPD/LAM/IAA/SSO/INTA/UPM/DASP/IDA', licence='CC BY-SA 4.0',
                       source='https://imagearchives.esac.esa.int/picture.php?/178085', caption="A pit in the Ma'at region, 4.8 km out · Rosetta's last day, 2016"),
                  dict(name='67p-boulders', src=O + 'comet67p-rosetta-descent-boulders-osiris-nac-N20160930T100706.png', kind='surface', body='Comet 67P',
                       quality=70, at=(0.6, 0.2), credit='ESA/Rosetta/MPS for OSIRIS Team MPS/UPD/LAM/IAA/SSO/INTA/UPM/DASP/IDA', licence='CC BY-SA 4.0',
                       source='https://imagearchives.esac.esa.int/picture.php?/178109', caption="Boulders on a pit's edge, 3.3 km out · Rosetta's last day, 2016"),
                  dict(name='67p-cliffs-descent', src=O + 'comet67p-rosetta-descent-maat-cliffs-osiris-wac-W20160930T090355.png', kind='surface',
                       body='Comet 67P', quality=70, credit='ESA/Rosetta/MPS for OSIRIS Team MPS/UPD/LAM/IAA/SSO/INTA/UPM/DASP/IDA', licence='CC BY-SA 4.0',
                       source='https://imagearchives.esac.esa.int/picture.php?/178968', caption="Cliffs and pits, 5.5 km out · Rosetta's last day, 2016")],
}
NEW_SMALL_WORLDS = [
    dict(name='dimorphos-last', src=O + 'dimorphos-dart-last-complete-image-12km-0401930049.png', kind='surface', body='Dimorphos', quality=70, flip=True,
         vignette=0.3, credit='NASA/Johns Hopkins APL', licence='Public domain',
         source='https://www.nasa.gov/solar-system/darts-final-images-prior-to-impact/',
         caption='Moonlet of the asteroid Didymos, 12 km out, two seconds before DART hit it · 2022'),
    dict(name='dimorphos-whole', src=O + 'dimorphos-dart-whole-moonlet-68km-0401930040.png', kind='surface', body='Dimorphos', quality=70, flip=True,
         credit='NASA/Johns Hopkins APL', licence='Public domain', source='https://www.nasa.gov/solar-system/darts-final-images-prior-to-impact/',
         caption='Moonlet of the asteroid Didymos, 68 km out · DART, 2022'),
    dict(name='eros-250m', src=O + 'eros-near-final-descent-250m-20010212e.tif', kind='surface', body='Eros', quality=80, vignette=0.3,
         credit='NASA/JHUAPL', licence='Public domain', source='https://near.jhuapl.edu/iod/20010212e/index.html',
         caption='250 m up, landing on an asteroid for the first time · NEAR Shoemaker, 2001'),
    dict(name='eros-120m', src=O + 'eros-near-last-image-120m-20010212f.tif', kind='surface', body='Eros', quality=80, crop=(0, 0, 1, 0.73), vignette=0.3,
         credit='NASA/JHUAPL', licence='Public domain', source='https://near.jhuapl.edu/iod/20010212f/index.html',
         caption='Its last picture, 120 m up · NEAR Shoemaker, 2001'),
]

PHOTOS = weave(PHOTOS, 'The Moon', MOON_SURFACE)
for body, surface in OTHER_SURFACE.items():
    PHOTOS = weave(PHOTOS, body, surface)
_after = max(i for i, p in enumerate(PHOTOS) if p['body'] == 'Lutetia') + 1
PHOTOS = PHOTOS[:_after] + NEW_SMALL_WORLDS + PHOTOS[_after:]
