"""Deep Space Tour's views: nebulae, star clusters, dying stars, galaxies, deep fields and the two black holes ever
imaged. Cut by ../solar-system/prep.py with TOUR=deep; see ../solar-system.md and ../deep-space.md for what the keys mean. `body` is the
object the tour moves between; `group` is what Settings → Show holds it on. Each object's views in the order the tour
shows them, best first. Real photos only: no artist's impressions, simulations or catalogue maps."""

HEADER = """# Deep Space Tour's views, cut by docs/solar-system/prep.py (TOUR=deep) from these originals. Public domain, CC BY or
# CC BY-SA; CC BY and CC BY-SA require this attribution. file\tbody\tcredit\tlicence\tsource\tcaption\tkind\tfocus x,y[,zoom]\tgroup
"""

HUBBLE = 'CC BY 4.0'


def whole(name, src, body, group, credit, licence, source, caption, **kw):
    """An object on dark sky, shown whole: the photo is already on black, so no levelling, just a soft edge."""
    d = dict(name=name, src=src, body=body, group=group, kind='disc', keepblack=True, box=(0, 0, 1, 1), margin=0, feather=0.05,
             cap=4096, credit=credit, licence=licence, source=source, caption=caption)
    d.update(kw)
    return {k: v for k, v in d.items() if v is not None}  # None drops a default (the black holes are levelled and boxed)


def closeup(name, src, body, group, credit, licence, source, caption, **kw):
    """A photo that fills the screen and pans."""
    return dict(name=name, src=src, body=body, group=group, kind='closeup', credit=credit, licence=licence, source=source,
                caption=caption, **kw)


G, R = '../deep/galaxies/', '../deep/remnants/'
DYING = 'Dying stars'

PHOTOS = [
    # Dying stars: planetary nebulae, supernova remnants and stars in outburst
    whole('ring-webb', R + 'ring-webb-nircam-2023.jpg', 'Ring Nebula', DYING, 'ESA/Webb, NASA, CSA, M. Barlow, N. Cox, R. Wesson', HUBBLE,
          'https://esawebb.org/images/weic2320b/', 'Webb, 2023 · infrared', at=(0.48, 0.47)),
    whole('southern-ring-webb', R + 'southern-ring-webb-nircam-2022.jpg', 'Southern Ring Nebula', DYING,
          'NASA, ESA, CSA, STScI, and the Webb ERO Production Team', HUBBLE, 'https://esawebb.org/images/weic2207b/', 'Webb, 2022 · infrared',
          at=(0.50, 0.46)),
    whole('southern-ring-spokes', R + 'southern-ring-webb-spokes-2022.jpg', 'Southern Ring Nebula', DYING,
          'NASA, ESA, CSA, STScI, O. De Marco (Macquarie University), J. DePasquale (STScI)', HUBBLE,
          'https://esawebb.org/images/southernring3/', 'Webb, 2022 · near and mid infrared', at=(0.45, 0.48)),
    closeup('helix-webb', R + 'helix-webb-nircam-2026.jpg', 'Helix Nebula', DYING, 'NASA, ESA, CSA, STScI, A. Pagan (STScI)', HUBBLE,
            'https://esawebb.org/images/weic2601a/', 'Its inner rim of comet-like knots · Webb, 2026 · infrared', shrink=0.5),
    whole('helix-hubble', R + 'helix-hubble-ctio-2003.jpg', 'Helix Nebula', DYING,
          'NASA, NOAO, ESA, the Hubble Helix Nebula Team, M. Meixner (STScI), and T.A. Rector (NRAO)', HUBBLE,
          'https://esahubble.org/images/heic0307a/', 'Hubble and Cerro Tololo, 2003', cap=3200, at=(0.45, 0.40)),
    whole('cats-eye', R + 'cats-eye-euclid-hubble-2026.jpg', "Cat's Eye Nebula", DYING,
          'ESA/Hubble & NASA, ESA Euclid/Euclid Consortium/NASA/Q1-2025, J.-C. Cuillandre & E. Bertin (CEA Paris-Saclay), Z. Tsvetanov', HUBBLE,
          'https://esahubble.org/images/potm2602c/', 'Hubble and Euclid, 2026', at=(0.50, 0.48), zoom=1.6),
    whole('butterfly', R + 'butterfly-ngc6302-hubble-2009.jpg', 'Butterfly Nebula', DYING, 'NASA, ESA and the Hubble SM4 ERO Team', HUBBLE,
          'https://esahubble.org/images/heic0910h/', 'Hubble, 2009 · narrowband color', at=(0.53, 0.46)),
    whole('red-spider', R + 'red-spider-ngc6537-webb-2025.jpg', 'Red Spider Nebula', DYING,
          'ESA/Webb, NASA & CSA, J. H. Kastner (Rochester Institute of Technology)', HUBBLE, 'https://esawebb.org/images/potm2510a/',
          'Webb, 2025 · infrared', at=(0.53, 0.46)),
    closeup('ngc6072', R + 'ngc6072-webb-nircam-2025.jpg', 'NGC 6072', DYING, 'NASA, ESA, CSA, STScI', HUBBLE,
            'https://esawebb.org/images/weic2514a/', 'A dying star in Scorpius · Webb, 2025 · infrared', at=(0.50, 0.52)),
    whole('cranium', R + 'exposed-cranium-pmr1-webb-nircam-2026.jpg', 'Exposed Cranium Nebula', DYING,
          'NASA, ESA, CSA, STScI, image processing: Joseph DePasquale (STScI)', HUBBLE, 'https://esawebb.org/images/weic2605c/',
          'Webb, 2026 · infrared', at=(0.48, 0.55)),
    whole('ngc5189', R + 'ngc5189-hubble-2012.jpg', 'NGC 5189', DYING, 'NASA, ESA and the Hubble Heritage Team (STScI/AURA)', HUBBLE,
          'https://esahubble.org/images/heic1220a/', 'A dying star in Musca · Hubble, 2012 · narrowband color', at=(0.55, 0.47)),
    closeup('crab-webb', R + 'crab-webb-2023.jpg', 'Crab Nebula', DYING, 'NASA, ESA, CSA, STScI, T. Temim (Princeton University)', HUBBLE,
            'https://esawebb.org/images/weic2326a/', 'Webb, 2023 · infrared', shrink=0.5, at=(0.52, 0.50)),
    whole('crab-hubble', R + 'crab-hubble-mosaic-2005.jpg', 'Crab Nebula', DYING,
          'NASA, ESA and Allison Loll/Jeff Hester (Arizona State University). Acknowledgement: Davide De Martin (ESA/Hubble)', HUBBLE,
          'https://esahubble.org/images/heic0515a/', 'Hubble, 2005 · narrowband color'),
    closeup('crab-core', R + 'crab-core-chandra-hubble-spitzer-2018.tif', 'Crab Nebula', DYING,
            'X-ray: NASA/CXC/SAO; Optical: NASA/STScI; Infrared: NASA-JPL-Caltech', 'Public domain', 'https://chandra.si.edu/photo/2018/crab/',
            'The pulsar at its heart · Chandra, Hubble and Spitzer, 2018 · X-ray, visible and infrared', at=(0.48, 0.48)),
    whole('cas-a-webb', R + 'cas-a-webb-nircam-2023.jpg', 'Cassiopeia A', DYING,
          'NASA, ESA, CSA, STScI, D. Milisavljevic (Purdue University), T. Temim (Princeton University), I. De Looze (University of Gent)', HUBBLE,
          'https://esawebb.org/images/weic2330a/', 'Webb, 2023 · infrared', at=(0.55, 0.30)),
    whole('cas-a-chandra', R + 'cas-a-chandra-webb-hubble-spitzer-2024.tif', 'Cassiopeia A', DYING,
          'X-ray: NASA/CXC/SAO; Optical: NASA/ESA/STScI; IR: NASA/ESA/CSA/STScI/Milisavljevic et al., NASA/JPL/CalTech; image processing: NASA/CXC/SAO/J. Schmidt and K. Arcand',
          'Public domain', 'https://chandra.si.edu/photo/2024/casa/', 'Chandra, Webb, Hubble and Spitzer, 2024 · X-ray, infrared and visible',
          at=(0.45, 0.48)),
    closeup('cas-a-hubble', R + 'cas-a-hubble-2006.jpg', 'Cassiopeia A', DYING,
            'NASA, ESA, and the Hubble Heritage (STScI/AURA)-ESA/Hubble Collaboration. Acknowledgement: Robert A. Fesen (Dartmouth College, USA) and James Long (ESA/Hubble)',
            HUBBLE, 'https://esahubble.org/images/heic0609a/', 'Its filaments · Hubble, 2006 · narrowband color', at=(0.47, 0.30)),
    closeup('veil', R + 'veil-hubble-2021.jpg', 'Veil Nebula', DYING, 'ESA/Hubble & NASA, Z. Levay', HUBBLE,
            'https://esahubble.org/images/potw2113a/', 'Hubble, 2021 · narrowband color'),
    closeup('vela', R + 'vela-snr-vst-2022-10k.tif', 'Vela Supernova Remnant', DYING,
            'ESO/VPHAS+ team. Acknowledgement: Cambridge Astronomical Survey Unit', HUBBLE, 'https://www.eso.org/public/images/eso2214a/',
            'ESO VLT Survey Telescope, 2022'),
    closeup('vela-bird', R + 'vela-snr-ghostly-bird-vst-2024.jpg', 'Vela Supernova Remnant', DYING,
            'ESO/VPHAS+ team. Acknowledgement: CASU', HUBBLE, 'https://www.eso.org/public/images/potw2403a/', 'ESO VLT Survey Telescope, 2024'),
    whole('pencil', R + 'vela-snr-pencil-eso-wfi-2012.jpg', 'Pencil Nebula', DYING, 'ESO', HUBBLE,
          'https://www.eso.org/public/images/eso1236a/', 'Part of the Vela supernova remnant · ESO, 2012', at=(0.40, 0.62)),
    whole('wr124', R + 'wr124-webb-2023.jpg', 'WR 124', DYING, 'NASA, ESA, CSA, STScI, Webb ERO Production Team', HUBBLE,
          'https://esawebb.org/images/weic2307a/', 'A star shedding its outer layers · Webb, 2023 · infrared', at=(0.52, 0.50)),
    whole('v838', R + 'v838-mon-hubble-2004.jpg', 'V838 Monocerotis', DYING, 'NASA, ESA, and The Hubble Heritage Team (AURA/STScI)', HUBBLE,
          'https://esahubble.org/images/heic0503a/', 'Its light echo · Hubble, 2004', at=(0.52, 0.50)),
    whole('tycho', R + 'tycho-snr-chandra-xray-2019.tif', "Tycho's Supernova Remnant", DYING, 'NASA/CXC/RIKEN & GSFC/T. Sato et al', 'Public domain',
          'https://chandra.si.edu/photo/2019/tycho/', 'Chandra, 2019 · X-ray, colored by element'),
    whole('kepler', R + 'kepler-snr-chandra-xray-2026.tif', "Kepler's Supernova Remnant", DYING, 'NASA/CXC/SAO', 'Public domain',
          'https://chandra.si.edu/photo/2026/kepler/', 'Chandra, 2026 · X-ray', shrink=0.4),
    whole('e0102', R + 'e0102-chandra-vlt-hubble-2018.tif', 'E0102', DYING, 'X-ray (NASA/CXC/ESO/F.Vogt et al); Optical (ESO/VLT/MUSE & NASA/STScI)',
          'Public domain and CC BY 4.0', 'https://chandra.si.edu/photo/2018/e0102/',
          'A supernova remnant in the Small Magellanic Cloud · Chandra, VLT and Hubble, 2018 · X-ray and visible', shrink=0.6),
    # Galaxies
    closeup('andromeda', G + 'm31-andromeda-hubble-phast-2025.jpg', 'Andromeda Galaxy', 'Galaxies', 'NASA, ESA, B. Williams (University of Washington)',
            HUBBLE, 'https://esahubble.org/images/heic2501a/', "Hubble's largest mosaic, 10 years in the making, 2025", crop=(0.08, 0.27, 0.965, 0.73), split=3),
    whole('whirlpool', G + 'm51-whirlpool-hubble-2005.jpg', 'Whirlpool Galaxy', 'Galaxies',
          'NASA, ESA, S. Beckwith (STScI), and The Hubble Heritage Team (STScI/AURA)', HUBBLE, 'https://esahubble.org/images/heic0506a/',
          'Hubble, 2005', at=(0.38, 0.48)),
    whole('pinwheel', G + 'm101-pinwheel-hubble-2006.jpg', 'Pinwheel Galaxy', 'Galaxies',
          'European Space Agency & NASA; Hubble data: K.D. Kuntz (GSFC), F. Bresolin (University of Hawaii), J. Trauger (JPL), J. Mould (NOAO), Y.-H. Chu (University of Illinois, Urbana); image processing: Davide De Martin (ESA/Hubble); CFHT: Canada-France-Hawaii Telescope/J.-C. Cuillandre/Coelum; NOAO: George Jacoby, Bruce Bohannan, Mark Hanna/NOAO/AURA/NSF',
          HUBBLE, 'https://esahubble.org/images/heic0602a/', 'Hubble, CFHT and Kitt Peak, 2006', at=(0.49, 0.50)),
    whole('sombrero', G + 'sombrero-hubble-2003.jpg', 'Sombrero Galaxy', 'Galaxies', 'NASA/ESA and The Hubble Heritage Team (STScI/AURA)', HUBBLE,
          'https://esahubble.org/images/opo0328a/', 'Hubble, 2003'),
    whole('sombrero-webb', G + 'sombrero-webb-nircam-2025.jpg', 'Sombrero Galaxy', 'Galaxies', 'NASA, ESA, CSA, STScI', HUBBLE,
          'https://esawebb.org/images/sombrerogalaxy1/', 'Webb, 2025 · infrared'),
    closeup('triangulum', G + 'm33-triangulum-hubble-2019.jpg', 'Triangulum Galaxy', 'Galaxies',
            'NASA, ESA, and M. Durbin, J. Dalcanton, and B. F. Williams (University of Washington)', HUBBLE,
            'https://esahubble.org/images/heic1901a/', "Hubble's 54-field mosaic, 2019", at=(0.45, 0.60)),
    whole('stephans-quintet', G + 'stephans-quintet-webb-2022.jpg', "Stephan's Quintet", 'Galaxies', 'NASA, ESA, CSA, and STScI', HUBBLE,
          'https://esawebb.org/images/weic2208a/', 'Webb, 2022 · infrared', at=(0.50, 0.45)),
    whole('cartwheel', G + 'cartwheel-webb-2022.jpg', 'Cartwheel Galaxy', 'Galaxies', 'NASA, ESA, CSA, STScI', HUBBLE,
          'https://esawebb.org/images/weic2211a/', 'Webb, 2022 · infrared', at=(0.63, 0.52)),
    whole('centaurus-a', G + 'centaurus-a-eso-wfi-2012.jpg', 'Centaurus A', 'Galaxies', 'ESO', HUBBLE, 'https://www.eso.org/public/images/eso1221a/',
          'ESO, 2012, from more than 50 hours of exposures', at=(0.50, 0.52)),
    closeup('centaurus-a-hubble', G + 'centaurus-a-hubble-2011.jpg', 'Centaurus A', 'Galaxies',
            "NASA, ESA, and the Hubble Heritage (STScI/AURA)-ESA/Hubble Collaboration. Acknowledgment: R. O'Connell (University of Virginia) and the WFC3 Scientific Oversight Committee",
            HUBBLE, 'https://esahubble.org/images/heic1110a/', 'Its dust lane · Hubble, 2011'),
    whole('cigar', G + 'm82-cigar-hubble-2006.jpg', 'Cigar Galaxy', 'Galaxies',
          'NASA, ESA and the Hubble Heritage Team (STScI/AURA). Acknowledgment: J. Gallagher (University of Wisconsin), M. Mountain (STScI) and P. Puxley (NSF)',
          HUBBLE, 'https://esahubble.org/images/heic0604a/', 'Hubble, 2006', at=(0.45, 0.25)),
    closeup('antennae', G + 'antennae-hubble-2013.jpg', 'Antennae Galaxies', 'Galaxies', 'ESA/Hubble & NASA', HUBBLE,
            'https://esahubble.org/images/potw1345a/', 'Hubble, 2013', at=(0.58, 0.30)),
    whole('arp273', G + 'arp273-rose-hubble-2011.jpg', 'Arp 273', 'Galaxies', 'NASA, ESA and the Hubble Heritage Team (STScI/AURA)', HUBBLE,
          'https://esahubble.org/images/heic1107a/', 'Two galaxies pulled into a rose · Hubble, 2011', at=(0.50, 0.25)),
    whole('rubins-galaxy', G + 'ugc2885-rubins-galaxy-hubble-2020.jpg', "Rubin's Galaxy", 'Galaxies',
          'NASA, ESA, and B. Holwerda (University of Louisville)', HUBBLE, 'https://esahubble.org/images/heic2002a/', 'UGC 2885 · Hubble, 2020',
          at=(0.51, 0.55)),
    whole('ngc1300', G + 'ngc1300-hubble-2005.jpg', 'NGC 1300', 'Galaxies', 'NASA, ESA, and The Hubble Heritage Team (STScI/AURA)', HUBBLE,
          'https://esahubble.org/images/opo0501a/', 'A barred spiral · Hubble, 2005', at=(0.49, 0.47)),
    whole('lmc', G + 'lmc-vista-2019.jpg', 'Large Magellanic Cloud', 'Galaxies', 'ESO/VMC Survey', HUBBLE,
          'https://www.eso.org/public/images/eso1914a/', 'ESO VISTA, 2019 · infrared', at=(0.35, 0.38)),
    whole('smc', G + 'smc-vista-2017.jpg', 'Small Magellanic Cloud', 'Galaxies', 'ESO/VISTA VMC', HUBBLE,
          'https://www.eso.org/public/images/eso1714a/', 'ESO VISTA, 2017 · infrared', at=(0.50, 0.45)),
    closeup('milky-way-centre', G + 'milky-way-centre-vista-vvv-2012.jpg', "The Milky Way's center", 'Galaxies',
            'ESO/VVV Survey/D. Minniti. Acknowledgement: Ignacio Toledo, Martin Kornmesser', HUBBLE, 'https://www.eso.org/public/images/eso1242a/',
            'ESO VISTA, 2012 · infrared', crop=(0, 0.12, 1, 0.48), split=2),
    whole('milky-way', G + 'milky-way-panorama-eso-brunier-2009.jpg', 'The Milky Way', 'Galaxies', 'ESO/S. Brunier', HUBBLE,
          'https://www.eso.org/public/images/eso0932a/', 'The whole sky from Chile, 2009', cap=6000, feather=0.02),
    # Deep fields and galaxy clusters
    closeup('hudf', G + 'hubble-ultra-deep-field-2004.jpg', 'Hubble Ultra Deep Field', 'Deep fields',
            'NASA, ESA, and S. Beckwith (STScI) and the HUDF Team', HUBBLE, 'https://esahubble.org/images/heic0406a/', 'Hubble, 2004', shrink=0.8),
    closeup('smacs0723', G + 'webb-first-deep-field-smacs0723-2022.jpg', "Webb's First Deep Field", 'Deep fields', 'NASA, ESA, CSA, and STScI',
            HUBBLE, 'https://esawebb.org/images/weic2209a/', 'SMACS 0723 · Webb, 2022 · infrared', at=(0.52, 0.50)),
    closeup('jades', G + 'jades-goods-south-webb-2023.jpg', 'JADES Deep Field', 'Deep fields',
            'NASA, ESA, CSA, B. Robertson (UC Santa Cruz), B. Johnson (Center for Astrophysics, Harvard & Smithsonian), S. Tacchella (University of Cambridge), M. Rieke (Univ. of Arizona), D. Eisenstein (Center for Astrophysics, Harvard & Smithsonian), A. Pagan (STScI)',
            HUBBLE, 'https://esawebb.org/images/JADES2/', 'Webb, 2023 · infrared'),
    closeup('pandora', G + 'pandoras-cluster-abell2744-webb-2023.jpg', "Pandora's Cluster", 'Deep fields',
            'NASA, ESA, CSA, I. Labbe (Swinburne University of Technology), R. Bezanson (University of Pittsburgh), A. Pagan (STScI)', HUBBLE,
            'https://esawebb.org/images/weic2305a/', 'Abell 2744 · Webb, 2023 · infrared', shrink=0.5),
    closeup('bullet', G + 'bullet-cluster-webb-2025.jpg', 'Bullet Cluster', 'Deep fields',
            'NASA, ESA, CSA, STScI, J. Jee (Yonsei University, UC Davis), S. Cha (Yonsei University), K. Finner (Caltech/IPAC)', HUBBLE,
            'https://esawebb.org/images/bullet-cluster/', 'Webb, 2025 · infrared'),
    closeup('perseus', G + 'perseus-cluster-euclid-2023.jpg', 'Perseus Cluster', 'Deep fields',
            'ESA/Euclid/Euclid Consortium/NASA, image processing by J.-C. Cuillandre (CEA Paris-Saclay), G. Anselmi', 'CC BY-SA 3.0 IGO',
            'https://www.esa.int/ESA_Multimedia/Images/2023/11/Euclid_s_view_of_the_Perseus_cluster_of_galaxies', 'Euclid, 2023 · visible and infrared',
            at=(0.45, 0.72)),
    closeup('virgo', G + 'virgo-treasure-chest-rubin-2025.jpg', 'Virgo Cluster', 'Deep fields', 'NSF–DOE Vera C. Rubin Observatory/NOIRLab/SLAC/AURA',
            HUBBLE, 'https://noirlab.edu/public/images/noirlab2521a/', "The Rubin Observatory's first look, 2025", at=(0.47, 0.34)),
    # The two black holes ever imaged
    whole('m87', R + 'm87-eht-2017-first-image-2019.jpg', 'M87*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://www.eso.org/public/images/eso1907a/', 'The first image of a black hole · Event Horizon Telescope, 2019 · radio',
          keepblack=False, box=None, margin=0.6),
    whole('sgr-a', R + 'sgr-a-eht-2017-2022release.tif', 'Sagittarius A*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://www.eso.org/public/images/eso2208-eht-mwa/', 'The black hole at the center of our galaxy · Event Horizon Telescope, 2022 · radio',
          feather=0.2),
]

N = '../deep/nebulae/'
NEB, CLUSTERS = 'Nebulae', 'Star clusters'
PHOTOS += [
    # Nebulae
    closeup('pillars-webb', N + 'pillars-webb-nircam-2022.jpg', 'Pillars of Creation', NEB, 'NASA, ESA, CSA, STScI; J. DePasquale, A. Koekemoer, A. Pagan (STScI)',
            HUBBLE, 'https://esawebb.org/images/weic2216b/', 'In the Eagle Nebula · Webb, 2022 · infrared', at=(0.70, 0.22)),
    closeup('pillars-hubble', N + 'pillars-hubble-wfc3-2014.jpg', 'Pillars of Creation', NEB, 'NASA, ESA/Hubble and the Hubble Heritage Team', HUBBLE,
            'https://esahubble.org/images/heic1501a/', 'In the Eagle Nebula · Hubble, 2015 · narrowband color', at=(0.38, 0.17)),
    closeup('cosmic-cliffs', N + 'cosmic-cliffs-webb-nircam-2022.jpg', 'Cosmic Cliffs', NEB, 'NASA, ESA, CSA, and STScI', HUBBLE,
            'https://esawebb.org/images/weic2205a/', 'NGC 3324, in the Carina Nebula · Webb, 2022 · infrared', at=(0.50, 0.45)),
    closeup('mystic-mountain', N + 'mystic-mountain-hubble-wfc3-2010.jpg', 'Mystic Mountain', NEB,
            'NASA, ESA and M. Livio and the Hubble 20th Anniversary Team (STScI)', HUBBLE, 'https://esahubble.org/images/heic1007c/',
            'In the Carina Nebula · Hubble, 2010 · narrowband color', at=(0.50, 0.30)),
    closeup('carina-hubble', N + 'carina-hubble-acs-mosaic-2007.jpg', 'Carina Nebula', NEB,
            'NASA, ESA, N. Smith (University of California, Berkeley), and The Hubble Heritage Team (STScI/AURA)', HUBBLE,
            'https://esahubble.org/images/heic0707a/', 'Hubble and Cerro Tololo, 2007 · narrowband color', at=(0.25, 0.45)),
    closeup('carina-treasure', N + 'carina-treasure-chest-webb-nircam-2026.jpg', 'Carina Nebula', NEB, 'ESA/Webb, NASA & CSA, M. Reiter', HUBBLE,
            'https://esawebb.org/images/potm2607a/', "The 'Treasure Chest' cluster · Webb, 2026 · infrared", at=(0.42, 0.38)),
    whole('carina-vst', N + 'carina-vst-eso-2012.jpg', 'Carina Nebula', NEB,
          'ESO. Acknowledgement: VPHAS+ Consortium/Cambridge Astronomical Survey Unit', HUBBLE, 'https://www.eso.org/public/images/eso1250a/',
          'ESO VLT Survey Telescope, 2012', at=(0.50, 0.30)),
    whole('orion-hubble', N + 'orion-hubble-acs-mosaic-2006.jpg', 'Orion Nebula', NEB,
          'NASA, ESA, M. Robberto (Space Telescope Science Institute/ESA) and the Hubble Space Telescope Orion Treasury Project Team', HUBBLE,
          'https://esahubble.org/images/heic0601a/', "Hubble's mosaic, 2006", at=(0.45, 0.42)),
    closeup('orion-hawki', N + 'orion-hawki-eso-2016.jpg', 'Orion Nebula', NEB, 'ESO/H. Drass et al.', HUBBLE,
            'https://www.eso.org/public/images/eso1625a/', 'ESO Very Large Telescope, 2016 · infrared', at=(0.60, 0.45)),
    whole('horsehead-euclid', N + 'horsehead-euclid-2023.jpg', 'Horsehead Nebula', NEB,
          'ESA/Euclid/Euclid Consortium/NASA, image processing by J.-C. Cuillandre (CEA Paris-Saclay), G. Anselmi', 'CC BY-SA 3.0 IGO',
          'https://www.esa.int/ESA_Multimedia/Images/2023/11/Euclid_s_view_of_the_Horsehead_Nebula', 'Euclid, 2023 · visible and infrared',
          at=(0.40, 0.64)),
    closeup('horsehead-webb', N + 'horsehead-webb-nircam-2024.jpg', 'Horsehead Nebula', NEB,
            'ESA/Webb, NASA, CSA, K. Misselt (University of Arizona) and A. Abergel (IAS/University Paris-Saclay, CNRS)', HUBBLE,
            'https://esawebb.org/images/weic2411a/', 'Its mane · Webb, 2024 · infrared', zoom=1.1),
    closeup('lagoon-hubble', N + 'lagoon-hubble-wfc3-2018.jpg', 'Lagoon Nebula', NEB, 'NASA, ESA, STScI', HUBBLE,
            'https://esahubble.org/images/heic1808a/', 'Its heart · Hubble, 2018', at=(0.42, 0.45)),
    whole('lagoon-eso', N + 'lagoon-wfi-eso-2009.jpg', 'Lagoon Nebula', NEB, 'ESO', HUBBLE, 'https://www.eso.org/public/images/eso0936a/',
          'ESO, 2009', at=(0.50, 0.55)),
    whole('trifid', N + 'trifid-rubin-2025.jpg', 'Trifid Nebula', NEB, 'NSF–DOE Vera C. Rubin Observatory/NOIRLab/SLAC/AURA', HUBBLE,
          'https://noirlab.edu/public/images/noirlab2521ah/', "The Rubin Observatory's first look, 2025", at=(0.50, 0.52)),
    closeup('tarantula', N + 'tarantula-webb-nircam-2022.jpg', 'Tarantula Nebula', NEB, 'NASA, ESA, CSA, and STScI', HUBBLE,
            'https://esawebb.org/images/weic2212a/', 'In the Large Magellanic Cloud · Webb, 2022 · infrared', at=(0.57, 0.55)),
    whole('rosette', N + 'rosette-decam-2024.jpg', 'Rosette Nebula', NEB,
          'CTIO/NOIRLab/DOE/NSF/AURA. Image processing: T.A. Rector (University of Alaska Anchorage/NSF NOIRLab), D. de Martin & M. Zamani (NSF NOIRLab)',
          HUBBLE, 'https://noirlab.edu/public/images/noirlab2424a/', 'Dark Energy Camera, 2024 · narrowband color', at=(0.65, 0.30)),
    closeup('rho-ophiuchi', N + 'rho-ophiuchi-webb-nircam-2023.jpg', 'Rho Ophiuchi', NEB,
            'NASA, ESA, CSA, STScI, K. Pontoppidan (STScI), A. Pagan (STScI)', HUBBLE, 'https://esawebb.org/images/weic2316a/',
            'The nearest star nursery · Webb, 2023 · infrared', at=(0.60, 0.12)),
    whole('ngc346', N + 'ngc346-webb-nircam-2023.jpg', 'NGC 346', NEB, 'NASA, ESA, CSA, STScI, A. Pagan (STScI)', HUBBLE,
          'https://esawebb.org/images/weic2301a/', 'A star nursery in the Small Magellanic Cloud · Webb, 2023 · infrared', at=(0.50, 0.45)),
    whole('cosmic-reef', N + 'cosmic-reef-hubble-2020.jpg', 'Cosmic Reef', NEB, 'NASA, ESA, and STScI', HUBBLE,
          'https://esahubble.org/images/heic2007a/', 'NGC 2014 and NGC 2020 · Hubble, 2020', at=(0.45, 0.45)),
    whole('bubble', N + 'bubble-hubble-wfc3-2016.jpg', 'Bubble Nebula', NEB, 'NASA, ESA, Hubble Heritage Team', HUBBLE,
          'https://esahubble.org/images/heic1608a/', 'Hubble, 2016 · narrowband color', at=(0.45, 0.45)),
    closeup('cats-paw', N + 'cats-paw-webb-nircam-2025.jpg', "Cat's Paw Nebula", NEB, 'NASA, ESA, CSA, STScI', HUBBLE,
            'https://esawebb.org/images/weic2513a/', 'Webb, 2025 · infrared', at=(0.57, 0.33)),
    closeup('pismis24', N + 'pismis24-webb-nircam-2025.jpg', 'Pismis 24', NEB, 'NASA, ESA, CSA, and STScI, A. Pagan (STScI)', HUBBLE,
            'https://esawebb.org/images/weic2518a/', 'In the Lobster Nebula · Webb, 2025 · infrared', at=(0.58, 0.60)),
    whole('hh46', N + 'hh46-47-webb-nircam-2023.jpg', 'Herbig–Haro 46/47', NEB, 'NASA, ESA, CSA, J. DePasquale (STScI)', HUBBLE,
          'https://esawebb.org/images/weic2319a/', 'Jets from two newborn stars · Webb, 2023 · infrared', at=(0.50, 0.48)),
    whole('s106', N + 's106-hubble-subaru-2011.jpg', 'Sharpless 2-106', NEB, 'NASA, ESA, the Hubble Heritage Team (STScI/AURA) and NAOJ', HUBBLE,
          'https://esahubble.org/images/heic1118b/', 'Hubble and Subaru, 2011 · infrared and hydrogen light', at=(0.52, 0.45)),
    whole('running-chicken', N + 'running-chicken-vst-eso-2023.jpg', 'Running Chicken Nebula', NEB, 'ESO/VPHAS+ team. Acknowledgement: CASU', HUBBLE,
          'https://www.eso.org/public/images/eso2320a/', 'ESO VLT Survey Telescope, 2023', at=(0.47, 0.42)),
    # Star clusters
    whole('pleiades', N + 'pleiades-kpno-noao.jpg', 'Pleiades', CLUSTERS,
          'NOIRLab/NSF/AURA/T.A. Rector (University of Alaska Anchorage), R. Cool (University of Arizona) and WIYN', HUBBLE,
          'https://noirlab.edu/public/images/noao-m45/', 'The Seven Sisters · Kitt Peak', at=(0.35, 0.50), zoom=1.15),
    whole('omega-centauri', N + 'omega-centauri-vst-eso-2011.jpg', 'Omega Centauri', CLUSTERS,
          'ESO/INAF-VST/OmegaCAM. Acknowledgement: A. Grado, L. Limatola/INAF-Capodimonte Observatory', HUBBLE,
          'https://www.eso.org/public/images/eso1119b/', 'ESO VLT Survey Telescope, 2011'),
    closeup('omega-centauri-core', N + 'omega-centauri-hubble-acs-2008.jpg', 'Omega Centauri', CLUSTERS,
            'NASA, ESA and the Hubble Heritage Team (STScI/AURA). Acknowledgement: A. Cool (San Francisco State Univ.) and J. Anderson (STScI)', HUBBLE,
            'https://esahubble.org/images/heic0809a/', 'Its crowded core · Hubble, 2008'),
    whole('47tuc', N + '47tuc-vista-eso-2013.jpg', '47 Tucanae', CLUSTERS,
          'ESO/M.-R. Cioni/VISTA Magellanic Cloud survey. Acknowledgment: Cambridge Astronomical Survey Unit', HUBBLE,
          'https://www.eso.org/public/images/eso1302a/', 'ESO VISTA, 2013 · infrared'),
    closeup('r136', N + 'r136-hubble-wfc3-2016.jpg', 'R136', CLUSTERS, 'NASA, ESA, P Crowther (University of Sheffield)', HUBBLE,
            'https://esahubble.org/images/heic1605a/', 'In the Tarantula Nebula · Hubble, 2016', at=(0.57, 0.72)),
    closeup('westerlund2', N + 'westerlund2-hubble-2015.jpg', 'Westerlund 2', CLUSTERS,
            'NASA, ESA, the Hubble Heritage Team (STScI/AURA), A. Nota (ESA/STScI), and the Westerlund 2 Science Team', HUBBLE,
            'https://esahubble.org/images/heic1509a/', "Hubble's 25th-anniversary picture, 2015", at=(0.58, 0.38)),
    whole('ngc602', N + 'ngc602-webb-nircam-miri-2024.jpg', 'NGC 602', CLUSTERS, 'ESA/Webb, NASA & CSA, P. Zeidler, E. Sabbi, A. Nota, M. Zamani (ESA/Webb)',
          HUBBLE, 'https://esawebb.org/images/weic2425a/', 'At the edge of the Small Magellanic Cloud · Webb, 2024 · infrared', at=(0.40, 0.45)),
    closeup('ngc3603', N + 'ngc3603-hubble-acs-2007.jpg', 'NGC 3603', CLUSTERS,
            'NASA, ESA and the Hubble Heritage (STScI/AURA)-ESA/Hubble Collaboration', HUBBLE, 'https://esahubble.org/images/heic0715a/',
            'Hubble, 2007', zoom=1.05),
]

# More official Event Horizon Telescope images of the same two black holes: M87* a year on, and both in polarised light.
PHOTOS += [
    whole('m87-2018', R + 'm87-eht-2018-2024release.png', 'M87*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://perimeterinstitute.ca/news/m87-one-year-later-proof-persistent-black-hole-shadow',
          'A year later, from 2018 data · Event Horizon Telescope, 2024 · radio', keepblack=None, box=None, margin=0.5, feather=0.08),
    whole('m87-polarised-2017', R + 'm87-eht-polarised-2017.png', 'M87*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://www.cfa.harvard.edu/news/new-eht-images-reveal-unexpected-polarization-flips-m87',
          'In polarized light, 2017 · Event Horizon Telescope · radio', keepblack=None, box=None, margin=0.5),
    whole('m87-polarised-2018', R + 'm87-eht-polarised-2018.png', 'M87*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://www.cfa.harvard.edu/news/new-eht-images-reveal-unexpected-polarization-flips-m87',
          'In polarized light, 2018 · Event Horizon Telescope · radio', keepblack=None, box=None, margin=0.5),
    whole('m87-polarised-2021', R + 'm87-eht-polarised-2021.png', 'M87*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://www.cfa.harvard.edu/news/new-eht-images-reveal-unexpected-polarization-flips-m87',
          'In polarized light, 2021, its field now spiraling the other way · Event Horizon Telescope · radio', keepblack=None, box=None, margin=0.5),
    whole('sgr-a-polarised', R + 'sgr-a-eht-polarised-2017-2024release.tif', 'Sagittarius A*', 'Black holes', 'EHT Collaboration', HUBBLE,
          'https://www.eso.org/public/images/eso2406a/', 'In polarized light · Event Horizon Telescope, 2024 · radio', feather=0.2),
]

# Dense star fields compress badly; at 50 they look the same on screen and take about a third less room.
for _p in PHOTOS:
    if _p['name'] in {'andromeda', 'lmc', 'smc', 'milky-way-centre', 'milky-way', 'omega-centauri-core', 'omega-centauri', '47tuc',
                      'perseus', 'virgo', 'triangulum', 'antennae', 'ngc3603', 'pandora'}:
        _p.setdefault('quality', 50)
